### ISSUE TITLE
Importing the track logs into mars

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-trackmate#1]
Hi Karl,

It would be great if the track logs and filter settings could be imported to mars along with the data. In the TrackMate GUI there are two logs created: one after peak detection, another one after tracking. The latter contains all parameters up and including tracking. However, to include all relevant parameters one has to click the 'information' button after setting the filters on the tracks as well. This log now also contains the parameters of the track filters. It would be best if that log could be incorporated, maybe even as text, into the metadata tab. 

Thank you for looking into this :)

**Comment by karlduderstadt** [comment]
Thanks for raising this issue. That was fixed a while ago for Trackmate v6 and now again for Trackmate v7 in commit 8e84b05ab37af6502607c526afe475991d5e5af9. This required some changes in Trackmate itself to expose the log again after all the updates in v7. More info about that [here](https://forum.image.sc/t/get-trackmate-log-in-action/57731).
